# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='jarsourceset',
  basename='protobuf-jarsourceset-example',
  source='ExampleProtobufExternalArchive.java',
  main='com.pants.examples.protobuf.jarsourceset.ExampleProtobufExternalArchive',
  dependencies=[
    'examples/src/protobuf/com/pants/examples/jarsourceset'
  ],
)
